export const surpriseIdeas = [
  "The companies building AI brains",
  "Who makes the chips inside everything?",
  "Powering the AI data-center boom",
  "Cybersecurity companies guarding the internet",
  "Cloud computing behind my favorite apps",
  "Quantum computing beyond the hype",
  "Rockets, satellites and life beyond Earth",
  "Robots and machines doing the hard work",
  "Electric vehicles and the future of driving",
  "Solar power, batteries and a cleaner grid",
  "Nuclear energy for a power-hungry world",
  "Biotech companies developing new medicines",
  "Companies behind gaming and virtual worlds",
  "Streaming, social media and the attention economy",
  "Digital banks and payment companies",
  "Crypto exchanges and digital-asset infrastructure",
  "Online shopping and the brands in my wardrobe",
  "Aerospace and defense technology",
  "ETFs that cover a whole market",
  "Companies with orange logos",
];
